services:
  sqlserver:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: mssql
    hostname: localhost
    ports:
      - '1434:1434'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1q2w3e4r!
    restart: always
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 1q2w3e4r! -C -Q 'SELECT 1' || exit 1",
        ]
      interval: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./mssql:/var/opt/mssql
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - '1411:1411'
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
